pluginVersion=1.1.1-beta

pluginId=com.gigaide.angular.ts
pluginName=Angular JS
pluginGroup=ru.sbrf.epoch.com.jetbrains.plugins

pluginSinceBuild=251
pluginUntilBuild=253.*

platformType=IC
ideaVersion=2025.1.3

jsdecorPluginZip=/media/Apacer1Tb/work26/jsdecor/build/distributions/javascript-2026.06.30-SNAPSHOT.zip
jsdecorCompileJar=/media/Apacer1Tb/work26/jsdecor/build/libs/javascript-2026.06.30-SNAPSHOT.jar
gigaideProJar=/home/mikle/.local/share/GIGAIDE/GIGAIDE-CE-2025.1/gigaide-pro/lib/gigaide-pro-1.0.6-dev.jar

kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
