pluginVersion=1.0.0-beta

# The version of ANTLR v4 that will be used to generate the parser
antlr4Version=4.9.3

pluginId=com.gigaide.angular.ts
pluginName=Angular JS
pluginGroup=ru.sbrf.epoch.com.jetbrains.plugins

pluginSinceBuild=251
pluginUntilBuild=251.*

platformType=IC
# Build locally for the newer platform version to ensure no errors will occur
# e.g. IC-2016.3.3, IU-2018.2.5 etc
# For a list of possible values, refer to the section 'com.jetbrains.intellij.idea' at https://www.jetbrains.com/intellij-repository/releases
ideaVersion=2025.1.3
#platformVersion=2024.2.1

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency=false
# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
